Modify method for connecting to ldap servers
liam-middlebrook/csh_ldap pull request #25
Opened 2020-09-24 02:37 UTC by adamhb123

This is necessary to retrieve the specific server to which ldap is connected, which is required in order to implement healthchecks (i.e. what is described here in [this issue](https://github.com/ComputerScienceHouse/profiles/issues/77).

2020-09-24 06:02 UTC, adamhb123 commented on csh_ldap/__init__.py
> +from ldap.ldapobject import SimpleLDAPObject
A misconception about what ReconnectLDAPObject actually does. I'll fix it now.

2020-09-24 17:15 UTC, mxmeinhold commented on csh_ldap/__init__.py
> +            raise ldap.SERVER_DOWN
I'm trying to figure out whether this loses us some of the advantage of having multiple ldap servers.
It's not in the ldap documentation, but glancing at the recconnectldapobject source, it looks like it will retry _all_ of the passed in uris when it goes to reconnect.

Since we have to specify only one uri to be able to do the healthcheck data, I think we should replicate this reconnection behavior ourselves. Perhaps that's a separate PR, but I think turning your connection for loop into a reconnect decorator might be the best path to take.

2020-09-24 17:17 UTC, mxmeinhold commented on csh_ldap/__init__.py
> +            raise ldap.SERVER_DOWN
If we do have an ldap server go down, then with this code, we'll have clients we need to manually reconnect. Even better than just automating the reconnect, it'd be really cool if you also rechecked the srv record, because then we'd automatically handle changes in the srv records.

2020-09-24 17:58 UTC, adamhb123 commented on csh_ldap/__init__.py
> +            raise ldap.SERVER_DOWN
Working on this right now, think I know how I want to do it. Will close this PR and open a new one when it is ready.

2020-09-24 20:22 UTC, adamhb123 commented on csh_ldap/__init__.py
> +            raise ldap.SERVER_DOWN
ha ha jk

2020-09-29 16:38 UTC, mxmeinhold requested changes
I think you should double check member.py and group.py. There are some methods there that I'm pretty sure use the connection without calling methods in this file, so exceptions there would not be caught by the reconnect decorator.

2020-09-29 16:38 UTC, mxmeinhold commented on csh_ldap/__init__.py
> +                continue
What happens here if every uri results in an exception?

2020-09-29 16:38 UTC, mxmeinhold commented on csh_ldap/__init__.py
> +        for uri in self.ldap_uris.split(',')[:-1]:
Why are you generating a list, joining it, then splitting it?
```suggestion
        self.ldap_uris = [f'ldaps://{uri.hostname}' for uri in ldap_srvs]
        self.server_uri = None

        for uri in self.ldap_uris:
```

2020-09-29 16:38 UTC, mxmeinhold commented on csh_ldap/__init__.py
> +                for uri in self.ldap_uris:
Same question as below about generating, joining, and resplitting a list. Also, what's the purpose of the `[2:][:-1]`?
```suggestion
                self.ldap_uris = [f'ldaps://{uri.hostname},' for uri in ldap_srvs]
                for uri in self.ldap_uris:
```

2020-09-29 16:38 UTC, mxmeinhold commented on csh_ldap/__init__.py
> +                False)
Your editor seems to be pretty zealous about changing whitespace. I don't think this is a problematic change, just something to be wary of.

2020-09-29 16:38 UTC, mxmeinhold commented on csh_ldap/__init__.py
> +            ['member'])
Ditto about whitespace.

2020-09-29 16:38 UTC, mxmeinhold commented on csh_ldap/__init__.py
>                  for dn in ret]
This might be a reasonable formatting change, though 10 spaces are a lot

2020-09-29 16:38 UTC, mxmeinhold commented on csh_ldap/__init__.py
>          return self.__con__
Probably don't need the decorator on this method, since it isn't using self.__con__, just returning it.

2020-10-03 17:58 UTC, mxmeinhold approved these changes
LGTM! :ship: :it:

Might be a good idea to add pylint and travis some time down the line so that things like the whitespace changes get more standardized, but it's not blocking, so I think this should be good to merge.

2020-10-07 17:22 UTC, mxmeinhold requested changes

2020-10-07 17:22 UTC, mxmeinhold commented on csh_ldap/__init__.py
> +            except Exception:
Shouldn't this only be for SERVER_DOWN and TIMEOUT? e.g. this should not be catching KeyError.

2020-10-10 01:20 UTC, mxmeinhold approved these changes
LGTM! :ship: :it:

2020-12-21 20:54 UTC, merged